# Generated by Django 6.0.3 on 2026-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_attendance_employee_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_staff', 'HR Staff'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
